"""empty message

Revision ID: 83775e54d7db
Revises: 
Create Date: 2019-11-27 18:12:05.831771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83775e54d7db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('context', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_action'), 'user', ['action'], unique=False)
    op.create_index(op.f('ix_user_context'), 'user', ['context'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_context'), table_name='user')
    op.drop_index(op.f('ix_user_action'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
