version: "3.7"
services:
    database:
        build: 
            context: .
            dockerfile: ./data_access/Dockerfile
        image: artefact_db_img
        container_name: artefact_db
        ports: 
            - 8765:5432
    backoffice:
        build: ./backoffice
        image: artefact_bo_img
        container_name: artefact_bo
        ports:
            - 8080:5000