"""add article id

Revision ID: aac4d61557f6
Revises: 
Create Date: 2020-04-06 22:55:58.009721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac4d61557f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_prev_action', sa.String(length=64), nullable=True),
    sa.Column('_context', sa.String(length=64), nullable=True),
    sa.Column('_last_article_index', sa.Integer(), nullable=True),
    sa.Column('_last_article_id', sa.Integer(), nullable=True),
    sa.Column('_rank_last_archive', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_user__context'), 'user', ['_context'], unique=False)
    op.create_index(op.f('ix_user__last_article_id'), 'user', ['_last_article_id'], unique=False)
    op.create_index(op.f('ix_user__last_article_index'), 'user', ['_last_article_index'], unique=False)
    op.create_index(op.f('ix_user__prev_action'), 'user', ['_prev_action'], unique=False)
    op.create_index(op.f('ix_user__rank_last_archive'), 'user', ['_rank_last_archive'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__rank_last_archive'), table_name='user')
    op.drop_index(op.f('ix_user__prev_action'), table_name='user')
    op.drop_index(op.f('ix_user__last_article_index'), table_name='user')
    op.drop_index(op.f('ix_user__last_article_id'), table_name='user')
    op.drop_index(op.f('ix_user__context'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
