"""empty message

Revision ID: c68813fa1f22
Revises: 
Create Date: 2020-01-09 11:11:24.386828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68813fa1f22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('_prev_action', sa.String(length=64), nullable=True),
    sa.Column('_context', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_user__context'), 'user', ['_context'], unique=False)
    op.create_index(op.f('ix_user__prev_action'), 'user', ['_prev_action'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__prev_action'), table_name='user')
    op.drop_index(op.f('ix_user__context'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
