"""added article tracking

Revision ID: f19b52a249ea
Revises: c68813fa1f22
Create Date: 2020-04-06 21:07:17.734713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19b52a249ea'
down_revision = 'c68813fa1f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_last_article_seen', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('_rank_last_archive', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user__last_article_seen'), 'user', ['_last_article_seen'], unique=False)
    op.create_index(op.f('ix_user__rank_last_archive'), 'user', ['_rank_last_archive'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__rank_last_archive'), table_name='user')
    op.drop_index(op.f('ix_user__last_article_seen'), table_name='user')
    op.drop_column('user', '_rank_last_archive')
    op.drop_column('user', '_last_article_seen')
    # ### end Alembic commands ###
